name: autoci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'platforms;android-34 build-tools;34.0.0'
      - name: Replace android.jar
        run: |
          curl -L https://github.com/Reginer/aosp-android-jar/raw/main/android-34/android.jar > $ANDROID_SDK_ROOT/platforms/android-34/android.jar
      - run: |
          ls $ANDROID_SDK_ROOT
          ls $ANDROID_SDK_ROOT/platforms
          ls $ANDROID_SDK_ROOT/platforms/android-34
          ls $ANDROID_SDK_ROOT/build-tools
          ls $ANDROID_SDK_ROOT/build-tools/34.0.0
      - name: Build release APK
        run: ./gradlew assembleRelease
      - name: Get short SHA
        run: echo "SHA7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
      - name: Upload Packages
        uses: actions/upload-artifact@master
        if: success()
        with:
          name: PixelIMS-debug-${{ env.SHA7 }}
          path: app/build/outputs/apk/release 